"""empty message

Revision ID: 631a44e80adc
Revises: 53fddd8fc622
Create Date: 2021-04-08 02:46:11.001360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631a44e80adc'
down_revision = '53fddd8fc622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
